# Generated by Django 4.1.7 on 2023-02-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='product_id',
        ),
    ]
